name: website-sveltekit build and test

on:
  push:
    paths:
      - 'website-sveltekit/**'
      - '.github/workflows/website-sveltekit-build.yml'
  pull_request:
    paths:
      - 'website-sveltekit/**'

permissions:
  contents: read
  issues: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: website-sveltekit/package-lock.json

      - name: Install dependencies
        working-directory: website-sveltekit
        run: npm ci --no-audit --no-fund

      - name: Validate graph.json (strict)
        working-directory: website-sveltekit
        run: npm run validate:graph:strict

      - name: Install Playwright (Chromium)
        working-directory: website-sveltekit
        run: npx playwright install --with-deps chromium

      - name: Build and run e2e tests
        working-directory: website-sveltekit
        env:
          CI: '1'
        run: |
          npm run build
          npx playwright test --reporter=list

      - name: Upload built site as artifact (preview)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: website-sveltekit-build
          path: website-sveltekit/build
          if-no-files-found: warn

  post-preview-comment:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post preview artifact link with counts
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'website-sveltekit/static/graph.json';
            let counts = { nodes: 'unknown', edges: 'unknown', generated: 'unknown' };
            try {
              const j = JSON.parse(fs.readFileSync(path,'utf8'));
              counts.nodes = j?.meta?.node_count ?? (j?.nodes?.length ?? 'unknown');
              counts.edges = j?.meta?.edge_count ?? (j?.edges?.length ?? 'unknown');
              counts.generated = j?.meta?.generated_at ?? 'unknown';
            } catch {}
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const body = [
              'Preview build artifact uploaded.',
              '',
              `• Nodes: ${counts.nodes}  • Edges: ${counts.edges}  • Generated: ${counts.generated}`,
              `• Run artifacts: ${runUrl}`,
              '• Artifact name: website-sveltekit-build',
              '',
              'Download the artifact and open index.html locally to preview (CSR only).'
            ].join('\n');
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body });
